# Generated by Django 2.2.27 on 2023-05-30 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.FileField(default='api_photo/1.jpg', upload_to='api_photo', verbose_name='Api封面')),
                ('title', models.CharField(default='', max_length=255, verbose_name='接口名称')),
                ('details', models.TextField(verbose_name='详情')),
                ('request_mode', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch'), ('head', 'head'), ('options', 'options')], default=1, max_length=20, verbose_name='访问类型')),
                ('data_type', models.CharField(choices=[('json', 'json'), ('xml', 'xml'), ('html', 'html'), ('picture', 'picture'), ('video', 'video'), ('str', 'str')], default=1, max_length=20, verbose_name='数据类型')),
                ('doc_url', models.CharField(default='', max_length=100, null=True, verbose_name='文档地址')),
                ('or_web_url', models.CharField(default='', max_length=100, null=True, verbose_name='来源地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': 'API列表',
                'db_table': 'api',
            },
        ),
        migrations.CreateModel(
            name='Api_tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=10, verbose_name='标签')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': 'API标签',
                'db_table': 'api_tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True, verbose_name='姓名')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='账户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('power', models.CharField(default='0', max_length=3, verbose_name='权限等级')),
                ('photo', models.FileField(default='user_photo/1.jpg', upload_to='user_photo', verbose_name='用户头像')),
                ('active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='User_login_code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=200, unique=True, verbose_name='账号')),
                ('code', models.CharField(default='', max_length=6, verbose_name='验证码')),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expire_time', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name_plural': '登录验证码',
                'db_table': 'User_login_code',
            },
        ),
        migrations.CreateModel(
            name='User_register_code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=200, unique=True, verbose_name='账号')),
                ('code', models.CharField(default='', max_length=6, verbose_name='验证码')),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expire_time', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name_plural': '注册验证码',
                'db_table': 'User_register_code',
            },
        ),
        migrations.CreateModel(
            name='User_access_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Api')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
            options={
                'verbose_name_plural': '用户浏览记录',
                'db_table': 'user_access_record',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Api')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
            options={
                'verbose_name_plural': 'Api评论',
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Api_visit_param',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50, verbose_name='参数昵称')),
                ('data_type', models.CharField(choices=[('number', 'number'), ('str', 'str'), ('boolean', 'boolean')], default='number', max_length=20, verbose_name='数据类型')),
                ('is_null', models.BooleanField(default=False, verbose_name='是否允许为空')),
                ('details', models.TextField(default='', verbose_name='详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Api')),
            ],
            options={
                'verbose_name_plural': 'API访问参数说明',
                'db_table': 'api_visit_param',
            },
        ),
        migrations.CreateModel(
            name='Api_respon_param',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_eg', models.TextField(default='', verbose_name='请求实例')),
                ('respon_eg', models.TextField(default='', verbose_name='返回实例')),
                ('request_mode', models.CharField(default='get', max_length=20, verbose_name='请求方式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Api')),
            ],
            options={
                'verbose_name_plural': 'API返回实例',
                'db_table': 'api_respon_param',
            },
        ),
        migrations.CreateModel(
            name='Api_likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=0, verbose_name='点赞状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Api')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
            options={
                'verbose_name_plural': 'API点赞',
                'db_table': 'api_likes',
            },
        ),
        migrations.CreateModel(
            name='Api_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislike', models.PositiveIntegerField(default=0)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='main.Api')),
            ],
            options={
                'verbose_name_plural': 'API信息',
                'db_table': 'api_info',
            },
        ),
        migrations.CreateModel(
            name='Api_favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Api')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
            options={
                'verbose_name_plural': 'API收藏',
                'db_table': 'api_favorites',
            },
        ),
        migrations.AddField(
            model_name='api',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.Api_tag'),
        ),
        migrations.AddConstraint(
            model_name='user_access_record',
            constraint=models.UniqueConstraint(fields=('api', 'user'), name='unique_access_record'),
        ),
        migrations.AddConstraint(
            model_name='api_likes',
            constraint=models.UniqueConstraint(fields=('api', 'user'), name='unique_like'),
        ),
        migrations.AddConstraint(
            model_name='api_favorites',
            constraint=models.UniqueConstraint(fields=('api', 'user'), name='unique_favorite'),
        ),
    ]
