# Generated by Django 2.2.27 on 2023-05-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_api_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
