# Generated by Django 2.2.27 on 2023-06-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_api_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_favorites',
            name='status',
            field=models.BooleanField(default=0, verbose_name='收藏状态'),
        ),
    ]
