# Generated by Django 2.2.27 on 2023-06-01 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_api_favorites_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_info',
            name='api',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apiinfo', to='main.Api'),
        ),
        migrations.CreateModel(
            name='Api_access_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Api')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
            options={
                'verbose_name_plural': 'API访问',
                'db_table': 'api_access_record',
            },
        ),
        migrations.CreateModel(
            name='Api_access',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.PositiveIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apiaccess', to='main.Api')),
            ],
            options={
                'verbose_name_plural': 'API访问统计表',
                'db_table': 'api_access',
            },
        ),
    ]
